
language: node_js
node_js:
  - 14
dist: xenial
#Tell Travis that we ndddeed super user permissions  

script:
- echo "skipping tests"

deploy:
  - provider: script
    script: node deploy.js pruebaDerko production
    skip_cleanup: true
    on:
      branch: main