
language: node_js
node_js:
  - 14
dist: xenial

script:
- echo "skipping tests"


deploy:
  provider: lambda
  function_name: "pruebaDerco5"
  region: "us-east-1"
  runtime: "nodejs12.x"
  handler_name: "handler"
  role: "arn:aws:iam::578807463618:role/service-role/rolLamda"
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  on:
    branch: main

  provider: lambda
  function_name: "pruebaDerco6"
  region: "us-east-1"
  runtime: "nodejs12.x"
  handler_name: "handler"
  role: "arn:aws:iam::578807463618:role/service-role/rolLamda"
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  on:
    branch: develop